In [124]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [126]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9703703703703703

In [127]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9962962962962963

In [128]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

In [129]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [130]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [131]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [132]:
get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test)
# Similarly we can check for other methods

0.9703703703703703

In [133]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)

In [134]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [135]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [136]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [137]:
scores_rf

[0.9332220367278798, 0.9532554257095158, 0.9265442404006677]

In [138]:
# while solving these real life problems you don't write this much just use cross_val_score
from sklearn.model_selection import cross_val_score

In [141]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)
# Similarly we can do for other ML methods

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])